project:
  type: website

resources: 
  - mvp_prediction.html

website:
  title: "NBA MVP MACHINE"
  navbar:
    left:
      - href: index.qmd
        text: Home page
      - about.qmd

format:
  html:
    respect-user-color-scheme: true
    theme: vapor
      
      #- cosmo
      #- brand
    css: styles.css
    toc: true



