project:
  type: website

resources: 
  - mvp_prediction.html
  - players.json

website:
  title: "NBA MVP MACHINE"
  navbar:
    left:
      - href: index.qmd
        text: Home page
      - href: calculator.qmd
        text: Calculate your own MVP
      - about.qmd


format:
  html:
    respect-user-color-scheme: true
    theme: vapor
      
      #- cosmo
      #- brand
    css: styles.css
    toc: true



