project:
  type: website

resources: 
  - mvp_prediction.html

website:
  title: "NBA_MVP_Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
      #- cosmo
      #- brand
    css: styles.css
    toc: true



