name: Render Quarto Site

on:
  push:
    branches:
    - main
    - fix-quarto-workflow
  pull_request:
    branches:
    - main
permissions:
  contents : write
    
jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: quarto render
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
